# Generated by Django 5.1.2 on 2024-11-08 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('stock_cantina', models.JSONField(default=dict)),
                ('ingresos_mensuales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complejos', to='usuarios.perfilcliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='canchas/')),
                ('nombre', models.CharField(max_length=200)),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('servicios', models.JSONField(default=dict)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='canchas.complejo')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sena_pagada', models.BooleanField(default=False)),
                ('cancelada', models.BooleanField(default=False)),
                ('hora_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('turno_servicios', models.CharField(blank=True, choices=[('MD', 'Medio día'), ('N', 'Noche')], max_length=2, null=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='canchas.cancha')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('tipo', models.CharField(choices=[('SENA', 'Seña'), ('TOTAL', 'Pago Total')], max_length=5)),
                ('referencia_pago', models.CharField(blank=True, max_length=100)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='canchas.reserva')),
            ],
        ),
    ]
