# Generated by Django 5.1.2 on 2024-11-08 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complejo',
            options={'verbose_name': 'Complejo', 'verbose_name_plural': 'Complejos'},
        ),
        migrations.AddField(
            model_name='complejo',
            name='hora_apertura',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Hora de apertura'),
        ),
        migrations.AddField(
            model_name='complejo',
            name='hora_cierre',
            field=models.TimeField(default=datetime.time(22, 0), verbose_name='Hora de cierre'),
        ),
    ]
