# Generated by Django 5.1.2 on 2024-11-11 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_alter_complejo_options_complejo_hora_apertura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='cancha',
            name='servicios',
        ),
        migrations.AddField(
            model_name='cancha',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='dias_disponibles',
            field=models.CharField(default='1,2,3,4,5,6,7', max_length=100),
        ),
        migrations.AddField(
            model_name='cancha',
            name='hora_fin',
            field=models.IntegerField(default=23),
        ),
        migrations.AddField(
            model_name='cancha',
            name='hora_inicio',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='cancha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='canchas/'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.complejo'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
